Fixed typos, syntax bugs and wrong file paths in Makefile for aplic(scalable)-imsic test
zero-day-labs/riscv-aia pull request #4
Opened 2023-08-17 16:31 UTC by KinzaQamar

This PR includes several fixes related to syntax, typos, and latch errors for Verilator v5.006. Additionally, the PR has only been tested for the configuration for aplic(scalable) with MSI mode.

2023-11-06 11:46 UTC, D3boker1 commented
Hi @KinzaQamar!

Thank you for your PR!

I leave some comments in your commits. I would really appreciate it if you could address them.

Additionally, I was going to ask you to clean up your commit history. I assume 2/3 should be enough. Because some modifications before the rebase end up being resolved there. So, if you could make the corrections starting from the current main it would be better. Any modifications that leads to commented code, it is best to remove it and not comment it.

2023-11-06 11:51 UTC, D3boker1 commented on rtl/aplic/common/aplic_defines.svh
> -`define DIRECT_MODE
Let's keep the default to `DIRECT_MODE`

2023-11-06 11:57 UTC, D3boker1 requested changes
Hi @KinzaQamar!

Thank you for your PR!

I leave some comments in your commits. I would really appreciate it if you could address them.

Additionally, I was going to ask you to clean up your commit history. I assume 2/3 should be enough. Because some modifications before the rebase end up being resolved there. So, if you could make the corrections starting from the current main it would be better. For any modifications that lead to commented code, it is best to remove it and not comment it.

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/common/axi4_lite_write_master.sv
> +    //input logic [3:0]                id_i,
Remove it completely.

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/common/aplic_defines.svh
> +//`define DIRECT_MODE
Let's keep the default to `DIRECT_MODE`

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/minimal/aplic_domain_notifier.sv
> +    parameter int unsigned                                          AXI_ADDR_WIDTH      = 64,
Remove any indentation-related modifications. I prefer to resolve it all at once in the future.

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/minimal/aplic_domain_notifier.sv
> +        //.id_i           ( id_i              ),
You can remove it completely

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/common/axi4_lite_write_master.sv
> +    //input logic [3:0]                id_i,
Also, when you address this comment, you can also remove the commented code within this file. Thus, we keep the deletions all together.

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/scalable/aplic_domain_notifier.sv
> +    //logic [3:0]                id_i;
Remove it. Also, remove the module parameter `ID`, since it is not used

2023-11-06 11:57 UTC, D3boker1 commented on rtl/aplic/scalable/aplic_top.sv
> +      o_req_msi.aw               = axi_req_s_domain.aw ;
Lets address the indentation problem in the future

2023-11-08 14:03 UTC, D3boker1 requested changes
Hi @KinzaQamar, 

Right now, you have 12 commits in this PR. As I requested before,  merge these changes into 3 commits (starting from the current main) and then force push into your branch so we can have a clean history. 

In my opinion the commits should be something like: 
1. [fix/aplic] remove AXI ID parameter and signal
2. [fix/aplic] fix aplic interface (use this  commit to fix the "," changes)
3. [fix/tests] fix test's makefile paths

2023-11-08 14:03 UTC, D3boker1 commented on rtl/aplic/common/aplic_defines.svh
> +//`define MSI_MODE
Please let's avoid these changes. Everything that is indentation I want to fix in a different commit.

2023-11-08 14:03 UTC, D3boker1 commented on rtl/aplic/scalable/aplic_top.sv
> +      o_req_msi.aw               = axi_req_s_domain.aw ;
You need to clear the past commits, otherwise, git will consider this as new

2023-11-08 17:02 UTC, KinzaQamar commented
@D3boker1 
> Right now, you have 12 commits in this PR. As I requested before, merge these changes into 3 commits (starting from the current main) and then force push into your branch so we can have a clean history.

Slight confusion. Didn't understand the current main part. I just need to pick and squash commits in interactive mode?

2023-11-08 17:19 UTC, D3boker1 commented
I believe the easiest path would be to fork the repo again, change the code following the commit scheme mentioned above, and force push to your branch (aia_op). But if you find a better way to do it, it is fine for me. The important is to have only that 3 commits, to keep the history clear for others to track changes.

2023-11-11 16:20 UTC, KinzaQamar commented
> This PR includes several fixes related to syntax, typos, and latch errors for Verilator v5.006. Additionally, the PR has only been tested for the configuration for aplic(scalable) with MSI mode.

Can you reveiw these changes on a different branch (https://github.com/zero-day-labs/riscv-aia/compare/master...KinzaQamar:riscv-aia:PR)

2023-11-12 12:57 UTC, D3boker1 commented
> > This PR includes several fixes related to syntax, typos, and latch errors for Verilator v5.006. Additionally, the PR has only been tested for the configuration for aplic(scalable) with MSI mode.
> 
> 
> 
> Can you reveiw these changes on a different branch (https://github.com/zero-day-labs/riscv-aia/compare/master...KinzaQamar:riscv-aia:PR)

It looks good to me! Force puch this new branch into the PR branch.

2023-11-12 14:16 UTC, KinzaQamar commented
> > > This PR includes several fixes related to syntax, typos, and latch errors for Verilator v5.006. Additionally, the PR has only been tested for the configuration for aplic(scalable) with MSI mode.
> > 
> > 
> > Can you reveiw these changes on a different branch ([master...KinzaQamar:riscv-aia:PR](https://github.com/zero-day-labs/riscv-aia/compare/master...KinzaQamar:riscv-aia:PR))
> 
> It looks good to me! Force puch this new branch into the PR branch.

Done!

2023-11-14 09:00 UTC, D3boker1 approved these changes
Looks good to me! Ty for your help @KinzaQamar!

2023-11-14 09:02 UTC, merged